allowBuilds:
  '@biomejs/biome': set this to true or false
  esbuild: set this to true or false
minimumReleaseAgeExclude:
  - '@invana/forms@0.0.11'
  - '@invana/styling@0.0.11'
  - '@invana/themes@0.0.11'
  - '@invana/ui@0.0.11'
  - '@invana/canvas-react@0.0.7'
  - '@invana/canvas@0.0.7'
  - '@invana/graph-layout-d3-force@0.0.7'
  - '@invana/graph-layout-elkjs@0.0.7'
  - '@invana/graph@0.0.7'
